#==========================================
# Camunda configs
#==========================================
camunda:
  baseUrl: http://localhost:8080/engine-rest
  workerId: workit
  maxTasks: 1
  topicName: topic_demo